version: "3.0"

networks:
  reactApp:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/usr/reactapp/src
      - ./${VITE_APP_PUBLIC_PATH}:/usr/reactapp/${VITE_APP_PUBLIC_PATH}
      - ./${VITE_APP_OUTPUT_PATH}:/usr/reactapp/${VITE_APP_OUTPUT_PATH}
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - "${VITE_APP_PORT}:${VITE_APP_PORT}"
    stdin_open: true
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${VITE_APP_PORT}"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 1s
    networks:
      - reactApp
