name: app-lint-and-build-check

env:
  VITE_APP_NAME                 : "Vite React Blueprint"
  VITE_APP_NAME_SHORT           : "Blueprint"
  VITE_APP_DESCRIPTION          : "Dummy description"
  VITE_APP_THEME_COLOR          : "#00bcd4"
  VITE_APP_BACKGROUND_COLOR     : "#efefef"
  VITE_BUILD_VERSION            : "0.0.1"
  VITE_APP_PORT                 : 3000
  VITE_ROOT_PATH                : "./"
  VITE_PUBLIC_PATH              : "./public"
  VITE_OUTPUT_PATH              : "./dist"
  VITE_PWA_DEV_OPTIONS_ENABLED  : true

on:
  push:
    branches:
      - master
      
jobs:
  app_lint_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Clone app
      uses: actions/checkout@v1
        
    - name: Install Dependencies & Run ESLint and Prettier check
      run: |
        npm install
        npm run lint
      
  app_build_check:
    runs-on: ubuntu-latest
    needs: [app_lint_check]
    env:
      VITE_PWA_DEV_OPTIONS_ENABLED: false
    
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Clone app
      uses: actions/checkout@v1
        
    - name: Install Dependencies & Build app
      run: | 
        npm install
        npm run build

    - name: List dist folder
      run: |
        ls -la ./dist
        ls -la ./dist/assets
        ls -la ./dist/css
        ls -la ./dist/i